export default {
  serviceCustomerList() {
    return {
      data: {
        list: [
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: 'E5400A3272C846FEB000C65713E81C0C',
            customerLevel: 0,
            customerName: '跟进dasdasdadasdas',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '84C2CF115BC34482B3E8A4EAA02893AD',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '2',
            customerLevel: 0,
            customerName: '说过话发挂号费改',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '3',
            customerLevel: 0,
            customerName: '古典风格的风格',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '4',
            customerLevel: 0,
            customerName: '就更好就更好',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '5',
            customerLevel: 0,
            customerName: '就更好就感觉刚好就干活',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
        ],
        pageNum: 0,
        pageSize: 0,
        total: 0,
      },
      eid: '',
      message: '',
      status: 200,
    };
  },
  // 查询停用客户列表
  stopCustomerList() {
    return {
      data: {
        list: [
          {
            bookkeepingAccounting: '1',
            createTime: '',
            customerId: '',
            customerName: '',
            stopReason: '',
            stopTime: '',
            vatType: 0,
          },
        ],
        pageNum: 0,
        pageSize: 0,
        total: 1,
      },
      eid: '',
      message: '',
      status: 200,
    };
  },

  updateCustomerStatus() {
    return {
      status: 200,
      message: 'mock',
      data: {
        failedList: [
          {
            msgId: 1,
            msgTitle: 'mock',
            msgContent: 'mock',
            customers: [
              {
                customerId: 'mock',
                customerName: 'mock',
                grantUsers: [
                  {
                    userId: 'mock',
                    username: 'mock',
                  },
                ],
              },
            ],
            sendTime: 1,
          },
        ],
        total: 1,
      },
    };
  },

  // 查询客户自定义列表表头信息
  getHeaderColumn() {
    return {
      data: [
        {
          fieldKey: 'customerName',
          fieldName: '客户名称',
          selected: true,
          sort: 1,
        },
        {
          fieldKey: 'customerCode',
          fieldName: '客户编码',
          selected: true,
          sort: 2,
        },
        {
          fieldKey: 'customerServiceRelationList',
          fieldName: '服务类型',
          selected: true,
          sort: 3,
        },
        {
          fieldKey: 'unifiedSocialCreditCode',
          fieldName: '社会统一信用码',
          selected: true,
          sort: 4,
        },
        {
          fieldKey: 'vatType',
          fieldName: '纳税性质',
          selected: true,
          sort: 5,
        },
        {
          fieldKey: 'industryType',
          fieldName: '行业类型',
          selected: false,
          sort: 6,
        },
        {
          fieldKey: 'isProductOil',
          fieldName: '成品油企业',
          selected: false,
          sort: 7,
        },
        {
          fieldKey: 'isForeignTrade',
          fieldName: '进出口企业',
          selected: false,
          sort: 8,
        },
        {
          fieldKey: 'registrationType',
          fieldName: '注册登记类型',
          selected: false,
          sort: 9,
        },
        {
          fieldKey: 'representative',
          fieldName: '法定代表人',
          selected: false,
          sort: 10,
        },
        {
          fieldKey: 'registeredCapital',
          fieldName: '注册资本',
          selected: false,
          sort: 11,
        },
        {
          fieldKey: 'establishmentDate',
          fieldName: '成立日期',
          selected: false,
          sort: 12,
        },
        {
          fieldKey: 'registrationAuthority',
          fieldName: '登记机关',
          selected: false,
          sort: 13,
        },
        {
          fieldKey: 'registrationAddress',
          fieldName: '注册地址',
          selected: false,
          sort: 14,
        },
        {
          fieldKey: 'businessScope',
          fieldName: '经营范围',
          selected: false,
          sort: 15,
        },
        {
          fieldKey: 'taxType',
          fieldName: '申报类型',
          selected: false,
          sort: 16,
        },
        {
          fieldKey: 'competentTaxAuthorities',
          fieldName: '主管税务机关',
          selected: false,
          sort: 17,
        },
        {
          fieldKey: 'isOpenTaxPlate',
          fieldName: '办理税盘',
          selected: false,
          sort: 18,
        },
        {
          fieldKey: 'isOpenCaCertificate',
          fieldName: '办理CA证书',
          selected: false,
          sort: 19,
        },
        {
          fieldKey: 'financialStatementsType',
          fieldName: '国税备案财务报表类型',
          selected: false,
          sort: 20,
        },
        {
          fieldKey: 'applyPeriod',
          fieldName: '申报周期',
          selected: false,
          sort: 21,
        },
        {
          fieldKey: 'commissioner',
          fieldName: '专管员姓名',
          selected: false,
          sort: 22,
        },
        {
          fieldKey: 'commissionerPhone',
          fieldName: '专管员电话',
          selected: false,
          sort: 23,
        },
        {
          fieldKey: 'customerLevel',
          fieldName: '客户等级',
          selected: false,
          sort: 24,
        },
        {
          fieldKey: 'documentNum',
          fieldName: '档案号',
          selected: false,
          sort: 25,
        },
        {
          fieldKey: 'customerSource',
          fieldName: '客户来源',
          selected: false,
          sort: 26,
        },
        {
          fieldKey: 'ticketType',
          fieldName: '取票方式',
          selected: false,
          sort: 27,
        },
        {
          fieldKey: 'bookkeepingAccounting',
          fieldName: '记账会计',
          selected: true,
          sort: 28,
        },
        {
          fieldKey: 'accountingAssistant',
          fieldName: '会计助理',
          selected: false,
          sort: 29,
        },
        {
          fieldKey: 'taxReportingAccounting',
          fieldName: '报税会计',
          selected: false,
          sort: 30,
        },
        {
          fieldKey: 'drawer',
          fieldName: '开票员',
          selected: false,
          sort: 31,
        },
        {
          fieldKey: 'customerConsultant',
          fieldName: '客户顾问',
          selected: false,
          sort: 32,
        },
        {
          fieldKey: 'normalContactName',
          fieldName: '联系人姓名',
          selected: false,
          sort: 33,
        },
        {
          fieldKey: 'normalContactPhone',
          fieldName: '联系人电话',
          selected: false,
          sort: 34,
        },
        {
          fieldKey: 'remark',
          fieldName: '备注',
          selected: false,
          sort: 35,
        },
        {
          fieldKey: 'accountingStatus',
          fieldName: '记账状态',
          selected: true,
          sort: 36,
        },
        {
          fieldKey: 'voucherCount',
          fieldName: '总凭证数',
          selected: true,
          sort: 37,
        },
        {
          fieldKey: 'voucherlineCount',
          fieldName: '总分录数',
          selected: true,
          sort: 38,
        },
        {
          fieldKey: 'createTime',
          fieldName: '创建时间',
          selected: true,
          sort: 39,
        },
      ],
      eid: '',
      message: 'OK',
      status: 200,
    };
  },

  // 修改客户自定义列表表头信息
  updateHeaderColumn() {
    return {
      data: {},
      eid: '',
      message: '',
      status: 200,
    };
  },
  // 查询客户自定义列业务类型信息
  getServiceType() {
    return {
      data: [
        {
          companyServiceTypeId: '0', // 服务类型id
          companyServiceTypeName: '工商注册', // 服务类型名称
          companyServiceTypeValue: 0, // 服务类型值
        },
        {
          companyServiceTypeId: '0', // 服务类型id
          companyServiceTypeName: '代理申报', // 服务类型名称
          companyServiceTypeValue: 3, // 服务类型值
        },
      ],
      eid: '',
      message: '',
      status: 200,
    };
  },
  // 查询部门树
  getDeptList() {
    return {
      data: [
        {
          children: [
            {
              children: [],
              deptId: '1',
              deptName: '子部门',
            },
          ],
          deptId: '0',
          deptName: '部门名称',
        },
      ],
      eid: '',
      message: '',
      status: 200,
    };
  },
};
