export default {
  serviceCustomerList() {
    return {
      data: {
        list: [
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: 'E5400A3272C846FEB000C65713E81C0C',
            customerLevel: 0,
            customerName: '跟进dasdasdadasdas',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '84C2CF115BC34482B3E8A4EAA02893AD',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '2',
            customerLevel: 0,
            customerName: '说过话发挂号费改',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '3',
            customerLevel: 0,
            customerName: '古典风格的风格',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '4',
            customerLevel: 0,
            customerName: '就更好就更好',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
          {
            accountingAssistant: '',
            accountingStatus: '',
            applyPeriod: 0,
            bookkeepingAccounting: '297E8DCD5508418E9890A3FD489BF77C',
            businessScope: '',
            commissioner: '',
            commissionerPhone: '',
            competentTaxAuthorities: '',
            createTime: '',
            customerCode: '',
            customerConsultant: '',
            customerId: '5',
            customerLevel: 0,
            customerName: '就更好就感觉刚好就干活',
            customerServiceRelationList: [
              {
                companyServiceTypeId: 0,
                companyServiceTypeValue: 0,
                customerId: '',
                edit: true,
                serviceTypeName: '',
              },
            ],
            customerShareholderInfoList: [
              {
                capitalContributionsAmount: 0,
                capitalContributionsDate: '',
                capitalContributionsType: '',
                certificateNum: '',
                reallyInvestAmount: 0,
                reallyInvestDate: '',
                reallyInvestType: '',
                reallyInvestmentAmount: 0,
                shareholder: '',
                shareholderCertificateType: 0,
                shareholderType: 0,
                subscriptionAmount: 0,
              },
            ],
            customerSource: 0,
            documentNum: '',
            drawer: '',
            establishmentDate: '',
            financialStatementsType: 0,
            industryType: '',
            industryTypeParent: '',
            isForeignTrade: 0,
            isOpenCaCertificate: 0,
            isOpenTaxPlate: 0,
            isProductOil: 0,
            normalContactName: '',
            normalContactPhone: '',
            registeredCapital: 0,
            registrationAddress: '',
            registrationAuthority: '',
            registrationType: 0,
            remark: '',
            representative: '',
            taxReportingAccounting: '',
            taxType: 0,
            ticketType: 0,
            unifiedSocialCreditCode: '',
            vatType: 0,
            voucherCount: 0,
            voucherlineCount: 0,
          },
        ],
        pageNum: 0,
        pageSize: 0,
        total: 0,
      },
      eid: '',
      message: '',
      status: 200,
    };
  },
  // 查询停用客户列表
  stopCustomerList() {
    return {
      data: {
        list: [
          {
            bookkeepingAccounting: '1',
            createTime: '',
            customerId: '',
            customerName: '',
            stopReason: '',
            stopTime: '',
            vatType: 0,
          },
        ],
        pageNum: 0,
        pageSize: 0,
        total: 1,
      },
      eid: '',
      message: '',
      status: 200,
    };
  },
};
